[versions]

compileSdk = "34"
minSdk = "26"
targetSdk = "34"
versionCode = "1"
versionName = "1.0"
jvmTarget = "17"
kotlinCompilerExtensionVersion = "1.5.0"

androidGradlePlugin = "8.0.2"
jetbrainsKotlin = "1.9.0"
hiltAndroid = "2.47"

androidXCore = "1.10.1"
androidxAppcompat = "1.6.1"
androidxLifecycle = "2.6.1"
androidxActivity = "1.7.2"

composeUiVersion = "1.4.3"
androidxComposeMaterial = "1.1.1"
junitVer = "4.13.2"
androidxTestExtjunit = "1.1.5"
androidxTestEspressoCore = "3.5.1"
androidxNavigationCompose = "2.6.0"
comGoogleAndroidMaterial = "1.9.0"

roomRersion = "2.5.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrainsKotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidXCore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
com-google-android-material = { module = "com.google.android.material:material", version.ref = "comGoogleAndroidMaterial" }

androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUiVersion" }
androidx-compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeUiVersion" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeUiVersion" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUiVersion" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeUiVersion" }

androidx-compose-material = { module = "androidx.compose.material3:material3", version.ref = "androidxComposeMaterial" }
junit = { module = "junit:junit", version.ref = "junitVer" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExtjunit" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspressoCore" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigationCompose" }

com-google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
com-google-dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRersion" }
